#!/bin/sh

##
# Simple BOOT.SCR Switcher
##

BOOTDIR=/flash
BOOTFILE=BOOT.SCR
BOOTSCRDIR=/usr/share/bootloader

help() {
  echo "$0 [resolution-file]"
  echo " resolution-file:"
  echo "   1080p"
  echo "   1080p-noedid"
  echo "   720p"
  echo "   720p-noedid"
  echo "   auto"
  echo "   debug"
  exit
}

mount() {
  /bin/busybox mount -o remount,$1 $BOOTDIR
}

get_mali() {
  HW=$(cat /proc/cpuinfo | grep ^Hardware | awk -F : '{print $2}' | sed 's, ,,')

  case $HW in
    ODROID-U2*)
      echo U2
      ;;
    ODROID-XU3)
      echo XU3
      ;;
    ODROIDX2)
      echo U2
      ;;
  esac
}

if [ "$(whoami)" != "root" ]; then
  echo "Please run as root user!"
  exit
fi


case $1 in
  1080p|1080P)
    mount rw
    cp -f $BOOTSCRDIR/$(get_mali)/boot-1080p.scr $BOOTDIR/$(get_mali)/$BOOTFILE
    sync
    mount ro
    ;;
  1080p-noedid|1080P-noedid)
    mount rw
    cp -f $BOOTSCRDIR/$(get_mali)/boot-1080p-noedid.scr $BOOTDIR/$(get_mali)/$BOOTFILE
    sync
    mount ro
    ;;
  720p|720P)
    mount rw
    cp -f $BOOTSCRDIR/$(get_mali)/boot-720p.scr $BOOTDIR/$(get_mali)/$BOOTFILE
    sync
    mount ro
    ;;
  720p-noedid|720P-noedid)
    mount rw
    cp -f $BOOTSCRDIR/$(get_mali)/boot-720p-noedid.scr $BOOTDIR/$(get_mali)/$BOOTFILE
    sync
    mount ro
    ;;
  auto)
    mount rw
    cp -f $BOOTSCRDIR/$(get_mali)/boot-auto.scr $BOOTDIR/$(get_mali)/$BOOTFILE
    sync
    mount ro
    ;;
  debug)
    mount rw
    cp -f $BOOTSCRDIR/$(get_mali)/boot-debug.scr $BOOTDIR/$(get_mali)/$BOOTFILE
    sync
    mount ro
    ;;
  *)
    help ;;
esac
