#!/bin/bash

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

TOPDIR=$(pwd)
GIT_FLAGS="${GIT_FLAGS:=-q}"
PKG_NAME="xf86-video-armsoc"

sources() {
  echo -n "Getting Sources ... "

  cd $TOPDIR

  if [ ! -d $PKG_NAME.git ]; then
    git clone $GIT_FLAGS git://anongit.freedesktop.org/xorg/driver/xf86-video-armsoc.git $PKG_NAME.git
  fi

  cd $TOPDIR/$PKG_NAME.git

  git reset $GIT_FLAGS --hard
  git clean $GIT_FLAGS -fd
  git pull $GIT_FLAGS

  if [ -n $1 ]; then
    git reset $GIT_FLAGS --hard $1
    GIT_REV=$1
  else
    GIT_REV=`git log -n1 --format=%h`
  fi

  echo "DONE"
}

package() {
  cd $TOPDIR

  if [ -d ${PKG_NAME}-${GIT_REV} ]; then
    echo -n "Cleaning Old Release ... "
    rm -rf ${PKG_NAME}-${GIT_REV}
    echo "DONE"
  fi

  echo -n "Copying GIT to Release ... "
  cp -RP $PKG_NAME.git ${PKG_NAME}-${GIT_REV}
  echo "DONE"

  echo -n "Cleaning Source ... "
  rm -rf ${PKG_NAME}-${GIT_REV}/.git
  echo "DONE"

  echo -n "Compressing Source ... "
  tar cJf ${PKG_NAME}-${GIT_REV}.tar.xz ${PKG_NAME}-${GIT_REV}
  echo "DONE"

  echo -n "Final Cleanup ... "
  rm -rf ${PKG_NAME}-${GIT_REV}
  echo "DONE"
}

sources $1
package
