#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

usage() {
  echo "$0 XU3|U2|C1"
  echo " ex. $0 XU3"
  exit 1
}

echo "getting sources..."
  case $1 in
    experimental|ex|ng)
      NG=1
      if [ ! -d u-boot-odroid-ng ]; then
        git clone git://github.com/hardkernel/u-boot.git u-boot-odroid-ng
      fi

      cd u-boot-odroid-ng
      ;;
    *)
      NG=0
      if [ ! -d u-boot-odroid ]; then
        git clone git://github.com/hardkernel/u-boot.git u-boot-odroid
      fi

      cd u-boot-odroid
      ;;
  esac

  git reset --hard
  git clean -fdx
  case $1 in
    XU3|xu3) git checkout -m odroidxu3-v2012.07 ;;
    U2|U3|u2|u3) git checkout -m odroid-v2010.12 ;;
    C1|c1) git checkout -m odroidc-v2011.03 ;;
    experimental|ex|ng) git checkout -m master ;;
  esac
  git pull
  [ -n $2 ] && git reset --hard $2
  GIT_REV=`git log -n1 --format=%h`
  sed -i "s|^EXTRAVERSION[[:space:]]*=.*$|EXTRAVERSION = +$GIT_REV|" Makefile
  VERSION="$(grep \^VERSION Makefile | head -1 | awk '{print $3}').$(grep \^PATCHLEVEL Makefile | awk '{print $3}')+$GIT_REV"
  cd ..

echo "copying sources..."
  rm -rf u-boot-$VERSION
  case $NG in
    0) cp -a u-boot-odroid u-boot-$VERSION ;;
    1) cp -a u-boot-odroid-ng u-boot-$VERSION ;;
  esac

echo "cleaning sources..."
  rm -rf u-boot-$VERSION/.git

echo "packing sources..."
  tar cJf u-boot-$VERSION.tar.xz u-boot-$VERSION

echo "remove temporary sourcedir..."
  rm -rf u-boot-$VERSION
