#!/bin/bash

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

TOPDIR=$(pwd)
GIT_FLAGS="-q"

usage() {
  echo "$0 XU3|U2|C1"
  echo "  ex. $0 XU3"
  exit 1
}

sources() {
  echo -n "Getting Sources ... "

  cd $TOPDIR

  if [ ! -d linux-odroid ]; then
    git clone $GIT_FLAGS git://github.com/hardkernel/linux.git linux-odroid
  fi

  cd $TOPDIR/linux-odroid

  git reset $GIT_FLAGS --hard
  git clean $GIT_FLAGS -fd

  case $1 in
    XU3|xu3) git checkout $GIT_FLAGS -m odroidxu3-3.10.y ;;
    U2|U3|u2|u3) git checkout $GIT_FLAGS -m odroid-3.8.y ;;
    c1|C1) git checkout $GIT_FLAGS -m odroidc-3.10.y ;;
    *) usage ;;
  esac

  git pull $GIT_FLAGS

  [ -n $2 ] && git reset $GIT_FLAGS --hard $2
  GIT_REV=`git log -n1 --format=%h`
  sed -i "s|^EXTRAVERSION[[:space:]]*=.*$|EXTRAVERSION = +$GIT_REV|" Makefile
  VERSION="$(grep \^VERSION Makefile | awk '{print $3}').$(grep \^PATCHLEVEL Makefile | awk '{print $3}').$(grep \^SUBLEVEL Makefile | awk '{print $3}')+$GIT_REV"

  echo "DONE"
}

package() {
  cd $TOPDIR

  if [ -d linux-$VERSION ]; then
    echo -n "Cleaning Old Release ... "
    rm -rf linux-$VERSION
    echo "DONE"
  fi

  echo -n "Copying GIT to Release ... "
  cp -RP linux-odroid linux-$VERSION
  echo "DONE"

  echo -n "Cleaning Source ... "
  rm -rf linux-$VERSION/.git
  echo "DONE"

  echo -n "Compressing Source ... "
  tar cJf linux-$VERSION.tar.xz linux-$VERSION
  echo "DONE"

  echo -n "Final Cleanup ... "
  rm -rf linux-$VERSION
  echo "DONE"
}

if [ -z $1 ]; then
  usage
else
  sources $1
  package $1
fi
