#!/bin/bash

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

TOPDIR=$(pwd)
GIT_FLAGS="${GIT_FLAGS:=-q}"
SAMSUNG_GIT="git://git.denx.de/u-boot-samsung.git"

usage() {
  echo "$0 XU3|U2|C1"
  echo "  ex. $0 XU3"
  exit 1
}

sources() {
  echo -n "Getting Sources ... "

  cd $TOPDIR

  if [ ! -d u-boot.git ]; then
    git clone $GIT_FLAGS $SAMSUNG_GIT u-boot.git
  fi

  cd $TOPDIR/u-boot.git

  git reset $GIT_FLAGS --hard
  git clean $GIT_FLAGS -fd

  case $1 in
    U2|u2|U3|u3|XU3|xu3) git checkout $GIT_FLAGS -m uboot ;;
    c1|C1) echo "Not yet implimented!" && exit 0 ;;
    *) usage ;;
  esac

  git pull $GIT_FLAGS

  if [ -n $2 ]; then
    git reset $GIT_FLAGS --hard $2
    git clean $GIT_FLAGS -fd
  fi

  GIT_REV=`git log -n1 --format=%h`
  sed -i "s|^EXTRAVERSION[[:space:]]*=.*$|EXTRAVERSION = +$GIT_REV|" Makefile
  VERSION="$(grep \^VERSION Makefile | awk '{print $3}').$(grep \^PATCHLEVEL Makefile | awk '{print $3}')+$GIT_REV"

  echo "DONE"
}

package() {
  cd $TOPDIR

  if [ -d u-boot-$VERSION ]; then
    echo -n "Cleaning Old Release ... "
    rm -rf u-boot-$VERSION
    echo "DONE"
  fi

  echo -n "Copying GIT to Release ... "
  cp -RP u-boot.git u-boot-$VERSION
  echo "DONE"

  echo -n "Cleaning Source ... "
  rm -rf u-boot-$VERSION/.git
  echo "DONE"

  echo -n "Compressing Source ... "
  tar cJf u-boot-$VERSION.tar.xz u-boot-$VERSION
  echo "DONE"

  echo -n "Final Cleanup ... "
  rm -rf u-boot-$VERSION
  echo "DONE"
}

if [ -z $1 ]; then
  usage
else
  sources $1 $2
  package $1
fi
