#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

echo "getting sources..."
  if [ ! -d linux-firmware.git ]; then
    git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git linux-firmware-git
  fi

  cd linux-firmware-git
    git pull
    GIT_REV="$(date +%Y%m%d).$(git rev-parse --short HEAD)"
  cd ..

echo "copying sources..."
  rm -rf samsung-firmware-$GIT_REV
  mkdir -p samsung-firmware-$GIT_REV
  cp -R linux-firmware-git/s5* samsung-firmware-$GIT_REV

echo "cleaning sources..."


echo "packing sources..."
  tar cvJf samsung-firmware-$GIT_REV.tar.xz samsung-firmware-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf samsung-firmware-$GIT_REV
