#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

echo "getting sources..."
  if [ ! -d linux-firmware-git ]; then
    git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git linux-firmware-git
  fi

  cd linux-firmware-git
    git pull
    GIT_REV="$(date +%Y%m%d).$(git rev-parse --short HEAD)"
  cd ..

echo "copying sources..."
  rm -rf rtlnic-firmware-$GIT_REV
  mkdir -p rtlnic-firmware-$GIT_REV
  cp -R linux-firmware-git/rtl_nic rtlnic-firmware-$GIT_REV
  cp -R linux-firmware-git/rtlwifi rtlnic-firmware-$GIT_REV

echo "cleaning sources..."


echo "packing sources..."
  tar cvJf rtlnic-firmware-$GIT_REV.tar.xz rtlnic-firmware-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf rtlnic-firmware-$GIT_REV
