#!/bin/bash

TOP_DIR=$(pwd | sed -e 's;/mkaddons;;' -e 's;/tools;;')

# Get current addon version
. $TOP_DIR/config/version

# Binary addons included in OE
BINARY_ADDONS=$( find $TOP_DIR/packages/mediacenter/kodi-binary-addons -maxdepth 1 -type d -exec basename {} \; | sed '1d' )

ADDONS=(
  "boblightd"
  "hdhomerun"
  "imon-mce"
  "sundtek-mediatv"
  "tvheadend"
  "repository.unofficial.addon.pro"
  "vdr-addon"
  $BINARY_ADDONS
)

PROJECTS=( "Odroid" )
DEVICES=( "U2" "XU3" "C1" )

for addon in ${ADDONS[@]} ; do
  for project in ${PROJECTS[@]} ; do
    for device in ${DEVICES[@]} ; do
      echo "PROJECT=${project} DEVICE=${device} $TOP_DIR/scripts/create_addon ${addon}"
      cd $TOP_DIR && \
        PROJECT=${project} DEVICE=${device} $TOP_DIR/scripts/create_addon ${addon}
    done
  done
done

for project in ${PROJECTS[@]} ; do
  for device in ${DEVICES[@]} ; do
    cd $TOP_DIR/target/addons/$ADDON_VERSION/${project}/${device} && \
      $TOP_DIR/tools/mkaddons/genrepo
  done
done
