#!/bin/sh

#TEMPLATE=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/sd-fuse-*))/sd-fuse_template
#TEMPLATE=$(pwd)/sd-fuse_template

#BS=512          # chunk size in bytes
#FUSE=6          # 6 sectors is 4k.  should be plenty for script to sit inside.
#IMG_START=4096  # 4096 is 2M.  we should be able to stick all our u-boot blobs inside the 2MB before our image.

# these could change, but its unlikely.
#U2_BL1_LOC=1
#U2_BL2_LOC=31
#U2_UBOOT_LOC=63
#U2_TZSW_LOC=2111

#XU3_BL1_LOC=1
#XU3_BL2_LOC=32
#XU3_UBOOT_LOC=63
#XU3_TZSW_LOC=719

# find out how many sectors each of the blobs take
#U2_BL1=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-u2-*))/sd_fuse/bl1.HardKernel
#U2_BL2=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-u2-*))/sd_fuse/bl2.HardKernel
#U2_UBOOT=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-u2-*))/u-boot.bin
#U2_TZSW=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-u2-*))/sd_fuse/tzsw.HardKernel
#XU3_BL1=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-xu3-*))/sd_fuse/hardkernel/bl1.bin.hardkernel
#XU3_BL2=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-xu3-*))/sd_fuse/hardkernel/bl2.bin.hardkernel
#XU3_UBOOT=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-xu3-*))/u-boot.bin
#XU3_TZSW=$ROOT/$BUILD/$(basename $(ls -d $ROOT/$BUILD/u-boot-odroid-xu3-*))/sd_fuse/hardkernel/tzsw.bin.hardkernel

#get_length() {
  dd if=$1 of=/dev/null > $ROOT/$BUILD/.stamps/gen_length 2>&1
  math=$(head -1 $ROOT/$BUILD/.stamps/gen_length | awk '{print $1}')
  echo $(($math))
#}

#U2_BL1_LENGTH=$(get_length $U2_BL1)
#U2_BL2_LENGTH=$(get_length $U2_BL2)
#U2_UBOOT_LENGTH=$(get_length $U2_UBOOT)
#U2_TZSW_LENGTH=$(get_length $U2_TZSW)
#XU3_BL1_LENGTH=$(get_length $XU3_BL1)
#XU3_BL2_LENGTH=$(get_length $XU3_BL2)
#XU3_UBOOT_LENGTH=$(get_length $XU3_UBOOT)
#XU3_TZSW_LENGTH=$(get_length $XU3_TZSW)

#sed -e "s/@U2_BL1_LENGTH@/$U2_BL1_LENGTH/" \
#    -e "s/@U2_BL2_LENGTH@/$U2_BL2_LENGTH/" \
#    -e "s/@U2_UBOOT_LENGTH@/$U2_UBOOT_LENGTH/" \
#    -e "s/@U2_TZSW_LENGTH@/$U2_TZSW_LENGTH/" \
#    -e "s/@XU3_BL1_LENGTH@/$XU3_BL1_LENGTH/" \
#    -e "s/@XU3_BL2_LENGTH@/$XU3_BL2_LENGTH/" \
#    -e "s/@XU3_UBOOT_LENGTH@/$XU3_UBOOT_LENGTH/" \
#    -e "s/@XU3_TZSW_LENGTH@/$XU3_TZSW_LENGTH/" \
#    -e "s/@FUSE@/$FUSE/" \
#    -e "s/@IMG_START@/$IMG_START/" \
#    -e "s/@U2_BL1_LOC@/$U2_BL1_LOC/" \
#    -e "s/@U2_BL2_LOC@/$U2_BL2_LOC/" \
#    -e "s/@U2_UBOOT_LOC@/$U2_UBOOT_LOC/" \
#    -e "s/@U2_TZSW_LOC@/$U2_TZSW_LOC/" \
#    -e "s/@XU3_BL1_LOC@/$XU3_BL1_LOC/" \
#    -e "s/@XU3_BL2_LOC@/$XU3_BL2_LOC/" \
#    -e "s/@XU3_UBOOT_LOC@/$XU3_UBOOT_LOC/" \
#    -e "s/@XU3_TZSW_LOC@/$XU3_TZSW_LOC/" \
#      $TEMPLATE > $ROOT/$BUILD/.stamps/sd-fuse.sh

