#!/bin/sh

usage(){ 
  echo "$0 U2|XU3 path/to/image|/dev/mmcblk0"
  exit
}

fuse() {
  dd $UBOOT_FLAGS if=$1 of=$2 seek=$3 > /dev/null 2>&1 || error
}

error() {
  echo "Error!"
  exit 1
}

[ -z $1 ] && usage
[ -z $2 ] && usage

if [ -z $INSTALL ]; then 
  . $(dirname $0)/../../config/version
  UBOOT_DIR="$(dirname $0)/../../$(basename $(ls -d $(dirname $0)/../../build.*${OPENELEC_VERSION}))/image/system/usr/share/bootloader"
else
  UBOOT_DIR=$INSTALL/usr/share/bootloader
fi
UBOOT_FLAGS="bs=512 conv=notrunc"

BL1=1
BL2=31
UBOOT=63
TZSW=2111

echo "Fusing: BL1 for Odroid-$1"
fuse $UBOOT_DIR/$1/bl1 $2 $BL1
echo "Fusing: BL2 for Odroid-$1"
fuse $UBOOT_DIR/$1/bl2 $2 $BL2
echo "Fusing: U-Boot for Odroid-$1"
fuse $UBOOT_DIR/$1/u-boot $2 $UBOOT
echo "Fusing: TrustZone S/W for Odroid-$1"
fuse $UBOOT_DIR/$1/tzsw $2 $TZSW
