#!/bin/sh

usage(){ 
  echo "$0 U2|XU3 path/to/image|/dev/mmcblk0"
  exit
}

fuse() {
  dd $UBOOT_FLAGS if=$1 of=$2 seek=$3 > /dev/null 2>&1
}

[ -z $1 ] && usage
[ -z $2 ] && usage

# Global
UBOOT_DIR=$INSTALL/usr/share/bootloader
UBOOT_FLAGS="iflag=dsync oflag=dsync conv=notrunc"

# Odroid-U2
U2_DIR=$UBOOT_DIR/U2
U2_BL1_START=1
U2_BL1_FILE=$U2_DIR/bl1
U2_BL2_START=31
U2_BL2_FILE=$U2_DIR/bl2
U2_UBOOT_START=63
U2_UBOOT_FILE=$U2_DIR/u-boot
U2_TZSW_START=2111
U2_TZSW_FILE=$U2_DIR/tzsw

# Odroid-XU3
XU3_DIR=$UBOOT_DIR/XU3
XU3_BL1_START=1
XU3_BL1_FILE=$XU3_DIR/bl1
XU3_BL2_START=31
XU3_BL2_FILE=$XU3_DIR/bl2
XU3_UBOOT_START=63
XU3_UBOOT_FILE=$XU3_DIR/u-boot
XU3_TZSW_START=719
XU3_TZSW_FILE=$XU3_DIR/tzsw

# Fuse
case $1 in
  U2)
    echo "Fusing: BL1 for Odroid-U2"
    fuse $U2_BL1_FILE $2 $U2_BL1_START
    echo "Fusing: BL2 for Odroid-U2"
    fuse $U2_BL2_FILE $2 $U2_BL2_START
    echo "Fusing: U-Boot for Odroid-U2"
    fuse $U2_UBOOT_FILE $2 $U2_UBOOT_START
    echo "Fusing: TrustZone S/W for Odroid-U2"
    fuse $U2_TZSW_FILE $2 $U2_TZSW_START
    ;;
  XU3)
    echo "Fusing: BL1 for Odroid-XU3"
    fuse $XU3_BL1_FILE $2 $XU3_BL1_START
    echo "Fusing: BL2 for Odroid-XU3"
    fuse $XU3_BL2_FILE $2 $XU3_BL2_START
    echo "Fusing: U-Boot for Odroid-XU3"
    fuse $XU3_UBOOT_FILE $2 $XU3_UBOOT_START
    echo "Fusing: TrustZone S/W for Odroid-XU3"
    fuse $XU3_TZSW_FILE $2 $XU3_TZSW_START
    ;;
esac
